### PR TITLE
Add basic serverside-rendering

### PR DESCRIPTION
**Pull request by nylser**
Deployment needs to be adjusted for using this

### CODE REVIEW

**Comment by rasaford** [comment]
[Universal Gotchas](https://github.com/angular/universal/blob/master/docs/gotchas.md)

**Comment by rasaford** [comment]
Poposal to delay this PR and focus on performance optimizations as a whole. Currently our Chrome performance score is quite low (23/100).
See more in the attached pdf
[chromium performance report.pdf](https://github.com/naklar-io/naklar.io/files/4506251/chromium.performance.report.pdf)

**Comment by nylser** [comment]
@rasaford performance stats are greatly improved with this (current branch on dev.naklar.io)

[PerformanceUniversal.pdf](https://github.com/naklar-io/naklar.io/files/4506319/PerformanceUniversal.pdf)

**Comment by rasaford** [comment]
Had a look at the code and it seems quite nice now! Made the following chages:

- Imported the existing proxy config for running in dev mode also in the SSR pages. 67b5afc1f21c329e8ad244bf109a0bb137436460
- Integrated the TransferAPI to prevent duplicate API calls to the backend. 7b2e16ce2fad439cf6d1e033d2817f4aedd215f8

**Comment by rasaford** [comment]
ToDos:

- [ ] Updating of the user guide for starting the dev server / deploying 
- [ ] Update `build.sh`script, configuring an express server to prerender the assets & serve them through `nginx`
- [ ] Maybe udpate `nginx` server to use `HTTP/2`

**Comment by nylser** [comment]
New youtube iframe changes make performance even better. [Performance Improvement.pdf](https://github.com/naklar-io/naklar.io/files/4508955/Performance.Improvement.pdf) 

I think after updating build/dev instructions, and updating the deployment for live naklar.io, we should merge this

**Comment by rasaford** [comment]
ready ?
if so merge :wink:

**Pull request merged**
